# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - np-chatter-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://naseracr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_4dd41d1be19a42c691f5893fc30d966e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4d114a6aacf24f169e0aa4f7cd7d7030 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: naseracr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4dd41d1be19a42c691f5893fc30d966e }}/chatter-backend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'np-chatter-backend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_8416e022602846409ecda6b654ae0297 }}
        images: 'naseracr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4dd41d1be19a42c691f5893fc30d966e }}/chatter-backend:${{ github.sha }}'