# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - np-chatter-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://naseracr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_308887af8f084db59b85e4f747ebb0ca }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6acf6df67d07410881c6d8e060d9cbb0 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: naseracr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_308887af8f084db59b85e4f747ebb0ca }}/np-chatter-backend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'np-chatter-backend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_029b306a69e34127a4cf4938beef9546 }}
        images: 'naseracr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_308887af8f084db59b85e4f747ebb0ca }}/np-chatter-backend:${{ github.sha }}'
        env: |
          MONGO_URI=${{ secrets.MONGO_URI }}
          PORT=${{ secrets.PORT }}
          DB_NAME=${{ secrets.DB_NAME }}
          NODE_ENV=${{ secrets.NODE_ENV }}
          ALLOWED_ORIGINS=${{ secrets.ALLOWED_ORIGINS }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          JWT_EXPIRES_IN=${{ secrets.JWT_EXPIRES_IN }}
          AZURE_STORAGE_CONNECTION_STRING=${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}